name: Secrets Healthcheck

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-github-pages:
    name: Check github-pages secrets
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      CONTACT_TO_EMAIL: ${{ secrets.CONTACT_TO_EMAIL }}
    steps:
      - name: Validate required secrets are present
        run: |
          missing=()
          [ -z "$RESEND_API_KEY" ] && missing+=(RESEND_API_KEY)
          [ -z "$CONTACT_TO_EMAIL" ] && missing+=(CONTACT_TO_EMAIL)
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
          echo "All required secrets are present in 'github-pages' environment."
