name: Secrets Healthcheck

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-production:
    name: Check production secrets
    runs-on: ubuntu-latest
    environment: production
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      CONTACT_TO_EMAIL: ${{ secrets.CONTACT_TO_EMAIL }}
      CONTACT_FROM_EMAIL: ${{ secrets.CONTACT_FROM_EMAIL }}
    steps:
      - name: Validate required secrets are present
        run: |
          missing=()
          [ -z "$RESEND_API_KEY" ] && missing+=(RESEND_API_KEY)
          [ -z "$CONTACT_TO_EMAIL" ] && missing+=(CONTACT_TO_EMAIL)
          [ -z "$CONTACT_FROM_EMAIL" ] && missing+=(CONTACT_FROM_EMAIL)
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
          echo "All required secrets are present in 'production' environment."

  check-staging:
    name: Check staging secrets
    runs-on: ubuntu-latest
    environment: staging
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      CONTACT_TO_EMAIL: ${{ secrets.CONTACT_TO_EMAIL }}
      CONTACT_FROM_EMAIL: ${{ secrets.CONTACT_FROM_EMAIL }}
    steps:
      - name: Validate required secrets are present
        run: |
          missing=()
          [ -z "$RESEND_API_KEY" ] && missing+=(RESEND_API_KEY)
          [ -z "$CONTACT_TO_EMAIL" ] && missing+=(CONTACT_TO_EMAIL)
          [ -z "$CONTACT_FROM_EMAIL" ] && missing+=(CONTACT_FROM_EMAIL)
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
          echo "All required secrets are present in 'staging' environment."
