name: Secrets Healthcheck

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-github-pages:
    name: Check github-pages Appwrite vars
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      NEXT_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT }}
      NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT_ID }}
      NEXT_PUBLIC_APPWRITE_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_DATABASE_ID }}
      NEXT_PUBLIC_APPWRITE_COLLECTION_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_COLLECTION_ID }}
    steps:
      - name: Validate required env vars are present
        run: |
          missing=()
          [ -z "$NEXT_PUBLIC_APPWRITE_ENDPOINT" ] && missing+=(NEXT_PUBLIC_APPWRITE_ENDPOINT)
          [ -z "$NEXT_PUBLIC_APPWRITE_PROJECT_ID" ] && missing+=(NEXT_PUBLIC_APPWRITE_PROJECT_ID)
          [ -z "$NEXT_PUBLIC_APPWRITE_DATABASE_ID" ] && missing+=(NEXT_PUBLIC_APPWRITE_DATABASE_ID)
          [ -z "$NEXT_PUBLIC_APPWRITE_COLLECTION_ID" ] && missing+=(NEXT_PUBLIC_APPWRITE_COLLECTION_ID)
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
          echo "All required Appwrite vars are present in 'github-pages' environment."
